### ISSUE TITLE
No org-babel-execute function for amm

### ISSUE THREAD

**Issue by 191205** [zwild/ob-ammonite#1]
Hello, I'm so happy to find such a plugin, the return result in very clean way.

I tried to fix this by reinstalling of ob-ammonite. but no luck

Thank you

**Comment by 191205** [comment]
Lol I forgot to do the following:
```
(after! org
  (def-package! ob-ammonite))

```

**Comment by 191205** [comment]
Everytime I run a new command, the next command I recive an error messsage: 
ammonite not running

**Comment by jonnylaw** [comment]
Same issue here, "Ammonite is not running" on Mac OS X with spacemacs.

**Comment by jonnylaw** [comment]
Okay, so if you run ammonite first, it works. Using M-x ammonite-term-repl

**Comment by suzzvv** [comment]
Yeah, you need to run it first. You can pull a request to update that part if you want.
