### ISSUE TITLE
Syntax Highlighting for amm block code ?

### ISSUE THREAD

**Issue by reyman** [zwild/ob-ammonite#3]
Thanks for this package, after discussion with dev of doom-emacs, amm is automaticly detected in org-babel block of source code.

One problem persist, syntax highlighting don't work after export, for example using ox-hugo, after export of source code block in markdown, "amm" langage is not recognized by any syntax highlighter... 

```amm
sealed trait Maybe[+T]
final case object Empty extends Maybe[Nothing]
final case class Just[T](t: T) extends Maybe[T]
```

Any idea to solve that using org headers ?

**Comment by suzzvv** [comment]
You could try
```
(add-to-list 'org-babel-tangle-lang-exts '("amm" . "scala"))
(add-to-list 'org-src-lang-modes '("amm" . scala))
```
Or
```
(require 'ob-ammonite)
```

**Comment by reyman** [comment]
Hum, i'm not sure my message was clear, amm is recognized by org, but during export on markdown, markdown blocks indicate \```amm and not \```scala fence block

**Comment by suzzvv** [comment]
Hi, I think you could write your own function to do that convertion thing.
